'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { BarChart3, Bell, CalendarDays, CheckSquare, CircleDollarSign, FileText, Home, LogOut, Menu, Settings2, Sparkles, UsersRound, X } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '@/hooks/use-auth'

const groups = [{ label: 'Visão geral', items: [{ icon: Home, href: '/psicologa/dashboard', label: 'Dashboard' }, { icon: CalendarDays, href: '/psicologa/agenda', label: 'Agenda' }] }, { label: 'Clínica', items: [{ icon: UsersRound, href: '/psicologa/pacientes', label: 'Pacientes' }, { icon: FileText, href: '/psicologa/prontuario', label: 'Prontuário' }, { icon: CheckSquare, href: '/psicologa/tarefas', label: 'Tarefas' }] }, { label: 'Gestão', items: [{ icon: CircleDollarSign, href: '/psicologa/financeiro', label: 'Financeiro' }, { icon: BarChart3, href: '/psicologa/relatorios', label: 'Relatórios' }] }]

export function Sidebar() { const pathname = usePathname(); const { logout } = useAuth(); const [mobileOpen, setMobileOpen] = useState(false); const isActive = (href: string) => pathname === href || pathname.startsWith(`${href}/`); const content = <div className="flex h-full flex-col gap-8 px-3 py-5"><div className="flex items-center gap-3 px-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></div><div><p className="text-sm font-semibold text-sidebar-foreground">Clínica<span className="text-primary">.</span></p><p className="text-[10px] uppercase tracking-widest text-sidebar-foreground/50">Espaço de cuidado</p></div></div><nav className="flex flex-1 flex-col gap-6">{groups.map((group) => <div key={group.label}><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-sidebar-foreground/40">{group.label}</p><div className="flex flex-col gap-1">{group.items.map(({ icon: Icon, href, label }) => <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive(href) ? 'bg-sidebar-accent text-sidebar-accent-foreground shadow-sm' : 'text-sidebar-foreground/65 hover:bg-sidebar-accent/60 hover:text-sidebar-foreground'}`}><Icon className="size-4" />{label}{label === 'Tarefas' && <span className="ml-auto rounded-full bg-primary/15 px-1.5 py-0.5 text-[10px] text-primary">2</span>}</Link>)}</div></div>)}</nav><div className="border-t border-sidebar-border pt-3"><Link href="/psicologa/configuracoes" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-sidebar-foreground/65 hover:bg-sidebar-accent/60"><Settings2 className="size-4" />Configurações</Link><button onClick={logout} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-sidebar-foreground/65 hover:bg-sidebar-accent/60"><LogOut className="size-4" />Sair</button></div></div>; return <><button aria-label="Abrir menu" onClick={() => setMobileOpen(true)} className="fixed left-4 top-4 z-40 rounded-xl border bg-card p-2 shadow-sm lg:hidden"><Menu className="size-4" /></button><aside className="hidden w-64 shrink-0 border-r bg-sidebar lg:block">{content}</aside>{mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Fechar menu" onClick={() => setMobileOpen(false)} className="absolute inset-0 bg-foreground/30" /><aside className="absolute inset-y-0 left-0 w-72 bg-sidebar shadow-xl">{content}<button onClick={() => setMobileOpen(false)} className="absolute right-4 top-4 text-sidebar-foreground"><X className="size-4" /></button></aside></div>}</> }
