'use client'

import { Bell, ChevronDown, Command, Search, Sun, Moon } from 'lucide-react'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { useAuth } from '@/hooks/use-auth'
import { useTheme } from '@/hooks/use-theme'
import Link from 'next/link'

export function TopBar() { const { user, logout } = useAuth(); const { theme, toggleTheme } = useTheme(); const initials = user?.name?.split(' ').map((n) => n[0]).join('').slice(0,2).toUpperCase() ?? 'HE'; return <header className="flex h-16 shrink-0 items-center justify-between border-b bg-background/90 px-5 backdrop-blur md:px-8"><button className="hidden w-full max-w-sm items-center gap-3 rounded-xl border bg-muted/40 px-3 py-2 text-left text-sm text-muted-foreground transition hover:bg-muted md:flex"><Search className="size-4" />Buscar em pacientes, agenda...<span className="ml-auto flex items-center gap-1 rounded-md border bg-background px-1.5 py-0.5 text-[10px]"><Command className="size-3" />K</span></button><div className="flex items-center gap-1 md:ml-auto"><Button variant="ghost" size="icon" className="rounded-xl" onClick={toggleTheme} aria-label="Alternar tema">{theme === 'light' ? <Moon className="size-4" /> : <Sun className="size-4" />}</Button><Button variant="ghost" size="icon" className="relative rounded-xl" aria-label="Notificações"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary" /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="ml-2 flex gap-2 rounded-xl px-2"><Avatar className="size-8"><AvatarFallback className="bg-primary/10 text-xs font-semibold text-primary">{initials}</AvatarFallback></Avatar><span className="hidden text-sm font-medium md:block">{user?.name?.split(' ')[0] ?? 'Helena'}</span><ChevronDown className="size-3 text-muted-foreground" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><div className="px-2 py-2"><p className="text-sm font-medium">{user?.name ?? 'Dra. Helena Martins'}</p><p className="text-xs text-muted-foreground">Psicóloga clínica</p></div><DropdownMenuSeparator /><DropdownMenuItem asChild><Link href="/psicologa/configuracoes">Meu perfil</Link></DropdownMenuItem><DropdownMenuItem asChild><Link href="/psicologa/configuracoes">Configurações</Link></DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={logout}>Sair da conta</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header> }
